### PR TITLE
gird change for both team and portofolio

### PR DESCRIPTION
**Pull request by plantvsbirds**
1. moved about section to back
2. better grid and layout for portfolio&team, on `xs` screens
3. better grid and layout for team, on `lg` screens
   image
   image
   image
   image

### CODE REVIEW

**Comment by plantvsbirds** [comment]
one more thing. removed margin at top. this is kinda debatable

**Comment by tengyifei** [comment]
very jizhi

**Comment by mar29th** [comment]
Projects are cramped towards left of the page.

**Comment by Yu-w** [comment]
@lafickens In preparation for three more projects - Yifei

**Pull request merged**
